<a href="https://colab.research.google.com/github/HaranJeon/python_programming/blob/main/11%EC%A3%BC%EC%B0%A8_%EC%84%9D%EC%82%AC%EA%B3%BC%EC%A0%95_%EC%A0%84%ED%95%98%EB%9E%80(2023135097).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

11주차 석사과정 전하란(2023135097)

https://numpy.org/doc/stable/user/absolute_beginners.html#

In [6]:
pip install numpy

How to import NumPy

In [7]:
import numpy as np

Reading the example code

In [8]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

What is an array?

In [12]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [13]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
print(a[0])

[1 2 3 4]


More information about arrays

In [15]:
import numpy as np
a = np.array([1, 2, 3])

In [16]:
np.zeros(2)

array([0., 0.])

In [17]:
np.ones(2)

array([1., 1.])

In [18]:
np.empty(2)

array([1., 1.])

In [19]:
np.arange(4)

array([0, 1, 2, 3])

In [20]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [21]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

Adding, removing, and sorting elements

In [23]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [24]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [26]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

How do you know the shape and size of an array?

In [28]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [29]:
array_example.size

24

In [30]:
array_example.shape

(3, 2, 4)

Can you reshape an array?

In [31]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [32]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [33]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [34]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [35]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [36]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [37]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [38]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [39]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [40]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

Indexing and slicing

In [41]:
data = np.array([1, 2, 3])

data[1]

2

In [42]:
data[0:2]

array([1, 2])

In [43]:
data[1:]

array([2, 3])

In [44]:
data[-2:]

array([2, 3])

In [45]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


In [46]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [47]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [48]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [49]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [50]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [51]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [52]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [53]:
print(a[b])

[1 2 3 4]


In [54]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


How to create an array from existing data

In [55]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [56]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [57]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [58]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [59]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [60]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [61]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [62]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
b2 = a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Basic array operations

In [64]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [65]:
data - ones

array([0, 1])

In [66]:
data * data

array([1, 4])

In [67]:
data / data

array([1., 1.])

In [68]:
a = np.array([1, 2, 3, 4])

a.sum()

10

In [69]:
b = np.array([[1, 1], [2, 2]])

In [70]:
b.sum(axis=0)

array([3, 3])

In [71]:
b.sum(axis=1)

array([2, 4])

Broadcasting

In [72]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [73]:
data.max()

2.0

In [74]:
data.min()

1.0

In [75]:
data.sum()

3.0

In [76]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

a.sum()

4.8595784

In [77]:
a.min()

0.05093587

In [78]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

Creating matrices

In [79]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [80]:
data[0, 1]

2

In [81]:
data[1:3]


array([[3, 4],
       [5, 6]])

In [82]:
data[0:2, 0]

array([1, 3])

In [83]:
data.max()

6

In [84]:
data.min()

1

In [85]:
data.sum()

21

In [86]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [87]:
data.max(axis=0)

array([5, 6])

In [88]:
data.max(axis=1)

array([2, 5, 6])

In [89]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [90]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [91]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [92]:
np.ones(3)

array([1., 1., 1.])

In [93]:
np.zeros(3)

array([0., 0., 0.])

In [94]:
rng = np.random.default_rng()
rng.random(3)

array([0.42820538, 0.22476476, 0.0884233 ])

In [95]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [96]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [97]:
rng.random((3, 2))

array([[0.2200271 , 0.46529558],
       [0.68628605, 0.63908661],
       [0.40587613, 0.45060025]])

Generating random numbers

In [98]:
rng.integers(5, size=(2, 4))

array([[0, 4, 4, 4],
       [1, 3, 2, 0]])

How to get unique items and counts

In [99]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [100]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [101]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [102]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [103]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [104]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [105]:
print(indices)

[0 1 2]


In [106]:
print(occurrence_count)

[2 1 1]


Transposing and reshaping a matrix

In [107]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [109]:
arr = np.arange(6).reshape((2, 3))

arr

array([[0, 1, 2],
       [3, 4, 5]])

In [110]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [111]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [112]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [113]:
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [114]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [115]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [116]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [117]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [118]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [119]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


Reshaping and flattening multidimensional arrays

In [120]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [121]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [122]:
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [123]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [124]:
a2 = x.ravel()
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [125]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
